name: Package Application with PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x86'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Application with PyInstaller
        run: pyinstaller --onefile --name IcarusLite-Win --icon=icarusicon.ico main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IcarusLite-Win\
          path: dist/IcarusLite-Win.exe
